BASE_URL = "https://gerrit.libreoffice.org"
PAGE_SIZE = 500
OUT_ROOT = "data"
CHANGES_ROOT = f"{OUT_ROOT}/changes"
CHECKPOINTS = f"{OUT_ROOT}/checkpoints"
REQUEST_OPTS = ["MESSAGES","DETAILED_LABELS","ALL_REVISIONS","DETAILED_ACCOUNTS","REVIEWER_UPDATES"]
